### ISSUE TITLE
A question about static files

### ISSUE THREAD

**Issue by colinshen** [127labs/generator-duxedo#10]
this is a style in this boilerplate. Does this mean I can only put my scss files in this forlder? 
and, 
what about pictures? suggestions?

**Comment by ghost** [comment]
Under the hood, generator-duxedo uses hjs-webpack by HenrikJoreteg. We've made sass-loader as the default loader. However, as mentioned [here](https://github.com/HenrikJoreteg/hjs-webpack#css), there are several options of css loaders that you can choose from. If you need stylus for example, just do `npm install stylus-loader --save-dev` and webpack will automatically pick up your stylus files. 

Similar case for static [assets](https://github.com/HenrikJoreteg/hjs-webpack#assets), you'll just need to `npm install url-loader --save-dev` and files of these extensions `jpg jpeg png gif svg otf eot svg ttf woff` will be automatically bundled into your release.

**Comment by colinshen** [comment]
@fardormu. Thanks for your help. When I am tryingto use your boilerplate, I had never used saga before. I spend some time to learn this package because I am new to react and redux. I think there are some new users have same problem. Do you think it would be better to make docs or add comments in your boilerplate that explain some codes?  e.g. selector.js. I was confused at first about this file. That was just a suggestion from a new user. By the way. thanks for your great work.

**Comment by ghost** [comment]
Thank you for your feedback. Yes, I agree with you. We Initially wanted to release a package where we ourselves could use at our convenience, but yes, some docs/comments would be helpful. If you think you could contribute while going through the codebase, feel free to open a PR. 

Also, I've written two part article starting [here](https://127labs.com/jumpstart-your-react-redux-development-with-duxedo/) on duxedo, check that out, maybe it could be helpful for you to grasp some of the basics.

I'm going to close this. Feel free to open another issue or PR about the documentation.

**Comment by colinshen** [comment]
I'm not a native English speaker, but I will do my best to do somethings. I will do it during my summer vacation.
