### ISSUE TITLE
Disable "Dynamic" routing

### ISSUE THREAD

**Issue by colinshen** [127labs/generator-duxedo#15]
Hi~
I have a problem when I use this generator. When I try to save ui state(dispatch the new ui state to state tree) when page changes, the new page still loads the default state. it seems every time page loaded the state tree is the default state tree so that I can not save loaded state in state tree. how can i disable this in this generator?

**Comment by imranismail** [comment]
Hi, did you mean you want to route the component according to the given url in the address bar?

**Comment by imranismail** [comment]
In the upcoming version, I'll enable browserHistory by default. I think you are facing this problem because we are using hashHistory.

**Comment by imranismail** [comment]
You can track the changes here https://github.com/127labs/generator-duxedo/pull/18
